name:             blog.mkii.org
author:           'Patrick Barrett'
description:      Various thoughts and projects
meta_description: "mkii.org, Varous thoughts and projects"
bio:              "My name is Patrick Barrett. I\'m an Applications Engineer at <a href='https://exosite.com'>Exosite</a> in Minneapolis, MN."

logo:             false
paginate:         15
baseurl:          /
domain_name:      'http://blog.mkii.org'
#google_analytics: 'UA-XXXXXXXX-X'

markdown:         redcarpet
highlighter:      pygments
